### ISSUE TITLE
Project shortcode

### ISSUE THREAD

**Issue by kilchenmann** [dhlab-basel/Salsah#107]
The shortcode needs to be supplied at the time of project creation. At the moment, the shortcode is optional, because not all our test data have it, but it is actually required for every new project. So in the GUI for project creation, it should be required.

The shortcode is a 4 digit hexadecimal number (0000 - FFFF) at least for now (see dhlab-basel/Knora#664).

The projects 0000 to 00FF are used for test purposes. In the beginning, Unil will use the project numbers 0100-07FF , and Unibas 0800 - 08FF. We should keep a list somewhere.

Each shortcode needs to be unique.

**Comment by lrosenth** [comment]
Hi,


in fact the GUI should be able at least to propose a new short code for projects. Probably we should have a central list (or a service) which distributes the unique  short codes.

I also think that we should forsee that the codes 0x0100-0xFFFF may not be sufficient in the (far) future...


Am 20.11.2017 um 14:21 schrieb André Kilchenmann <notifications@github.com<mailto:notifications@github.com>>:


The shortcode needs to be supplied at the time of project creation. At the moment, the shortcode is optional, because not all our test data have it, but it is actually required for every new project. So in the GUI for project creation, it should be required.

The shortcode is a 4 digit hexadecimal number (0000 - FFFF) at least for now (see dhlab-basel/Knora#664<https://github.com/dhlab-basel/Knora/issues/664>).

The projects 0000 to 00FF are used for test purposes. In the beginning, Unil will use the project numbers 0100-07FF , and Unibas 0800 - 08FF. We should keep a list somewhere.

Each shortcode needs to be unique.

**Comment by kilchenmann** [comment]
I will use the "short name" field for the shortcode. I think we do not need so many fields to create a project. With the post proecess we set the same value for short name as we have in shortcode? Does it make sense?

**Comment by subotic** [comment]
No, we use and need both internally. The data graph, for example, has the following form: `http://www.knora.org/data/[shortcode/]shortname`

Also, `shortname` is used in Salsah 1.5. Showing the user `00FF` is not the same as `images`. Keep in mind that projects created with the new admin GUI need to work with Salsah 1.5, which is our production GUI.

Depending on where and how `shortname` will be used in the future, it shouldn't be allowed to start with a number: https://github.com/dhlab-basel/Knora/issues/667

**Comment by kilchenmann** [comment]
Yes, I know. I just wanted to have less input fields. After writing the comment I was thinking about the same, what you said just now: `00FF is not the same as images` ...
So, I have to rearrange the whole project form, which isn't so simple. But I will find a solution...
Btw I'm creating a list of projects incl. the shortcode overview.
