### ISSUE TITLE
Extended Search: Property not exists

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Salsah#110]
add a comparison operator "not exists" so that we can check for the absence of a property.

use case: search a book without a description.

**Comment by musicEnfanthen** [comment]
This will be a very helpful feature!

It is not trivial to model non-existing properties. So, how would you translate such a gui operator to a sparql query, since there are at least three ways: 

`FILTER (!bound (?var))`

(only since v 1.1):
`NOT EXISTS (?s prop ?o)` (returns only the results where the specified path does not exist)

`MINUS (?s prop ?o)` (returns all results and removes afterwards those where the specified path does exist)

When I remember correctly, the results can differ for certain kind of queries depending on the operator that is used.

**Comment by tobiasschweizer** [comment]
In KnarQL, we already support `FILTER NOT EXISTS`.
