### ISSUE TITLE
Central repository for deployment manual of Knora, Salsah and Sipi

### ISSUE THREAD

**Issue by janCstoffregen** [dhlab-basel/Salsah#166]
Issue related to https://github.com/dhlab-basel/Knora/issues/728#issuecomment-364409032

Dear @benjamingeer , this is an issue that refers to all parts of the software, I thought it might be useful for a user that is not quite yet familiar with the whole concept to provide an entry point, where there is one place where the user can see exactly how he or she can deploy the whole software. Salsah alone does not make much sense without all other three parts, for example.

So I wonder
- How can the user guess that he or she has to look at the Knora repository for instructions for the whole deployment?
- Furthermore, if the user has bugs while deploying the software (without changing any part of it), it is definitely convenient for you if the user finds a solution himself. It is more likely that the user finds the solution for an occurred problem if all issues that come up during the deployment are collected at one spot.

At the moment, the user has to read the following sources to be able to deploy all parts of the software:
Knora:
- https://github.com/nie-ine/Knora
- http://www.knora.org/documentation/
- https://libraries.io/github/dhlab-basel/Knora

Salsah:
- https://github.com/dhlab-basel/Salsah
- https://dhlab-basel.github.io/Salsah/
- https://libraries.io/github/dhlab-basel/Salsah

Sipi:
- https://github.com/dhlab-basel/Sipi
- http://www.knora.org/documentation/manual/rst/sipi/index.html
- https://dhlab-basel.github.io/Sipi/documentation/running.html
- https://libraries.io/github/dhlab-basel/Sipi

GraphDB:
- https://github.com/dhlab-basel/Knora
- https://libraries.io/github/dhlab-basel/docker-graphdb

( and I think even more … )

I estimate that you have to first find and then read at least 30 pages of instructions which are spread out through the whole documentation. Furthermore, it is very hard to find the information that there are actually Docker images that you can use to install everything within a couple of minutes.

The page https://libraries.io/ is necessary as well because there is not only redundant information. For Sipi, it explains for example how to set it up in a centos environment. Since there is no link to this website, you have to guess that this exists as well.

If there would be one central deployment description for all, it would save a lot of time for KnoSaSiGraphDB newbies and it would save money respectively for the projects that they work for. I would be glad to assist in writing the description how to deploy everything. If you would open a repository I will start right away. The content would be the docker compose script and a table of versions that work with one another and further deploying information. If we do this, the user has to only read one page to deploy everything. After your deployment solution is ready, you can update the repository respectively. Would it be ok if you open another repository for the deployment of all parts?

Thank you for your answer and have a nice weekend,
Jan

**Comment by lrosenth** [comment]
Hi Jan,

good point You make! I agree that we need a better documentation (or even some tools) that help to deploy the system for the non-nerd user.

Thanks!

**Comment by janCstoffregen** [comment]
Hi Lukas,
I'm glad that you agree! I would be glad if you let me know how I can assist and what you think about a central repository for the deployment manual.

**Comment by benjamingeer** [comment]
Hi Jan,

I agree that we need more and better documentation. Your contributions to the documentation would be most welcome.

> How can the user guess that he or she has to look at the Knora repository for instructions for the whole deployment?

The framework as a whole is called Knora. It seems to me that the "entry point" that you are asking for already exists: http://www.knora.org, which has direct links to the documentation in the Knora GitHub repository. Definitely the content of http://www.knora.org needs to be improved, and I think that would be a good place to put a "quick start" deployment guide.

However, Knora is a framework with several different parts. Not all users will want to use all parts. Sipi can be used by itself. Knora can be used without Salsah or Sipi. We can't assume that all users will want to deploy everything.

Each of these parts is indeed complex. We are trying to make a highly flexible and generic system, which means that the user has a great deal of power. Understanding how to use this power requires a lot of documentation. Putting the 30 pages of documentation on one web site will not mean that it will take less time for the user to read it.

You say that the user "has to read the following sources" including https://github.com/nie-ine/Knora But that is NIE-INE's fork of Knora. You are of course free to fork Knora, but we never suggested that you should do so.

I have never heard of https://libraries.io/ and never needed to use it to set up Sipi. I wrote the documentation on compiling Sipi on CentOS (https://dhlab-basel.github.io/Sipi/documentation/building.html#centos-7). If this documentation isn't correct, please open an issue about it.

**Comment by janCstoffregen** [comment]
Dear @benjamingeer ,
I did not want to say anything against the capability of the system, I'd like to honestly apologise if it sounded like this.

A quick start guide is a great idea, I will be glad to assist in writing it and will start right away, thank you for this suggestion.

I meant the dhlab fork, sorry for this mistake.

I disagree that 30 pages are necessary to get the system up and running. I agree that you need extensive documentation to use the system in depth and to further develop it, but not to get it up and running. That is not common since you can automise most steps. For instance, I would like to mention in the documentation how to set up sipi on centos that there is a sipi - base docker image, so that the user does not have to install all packages manually any more.

Thank you very much for your answer and best regards,
Jan

**Comment by lrosenth** [comment]
Hi to all,

I thonk we must do a quick start guide that’s verse short and terse - with references to the exhaustive documentation so that people who want/must know more can go there.

In addition I hope that we can make the installation much simpler using docker... right now I see that it is difficult, but with some effort it certainly can be done... May be I can add this as a workpage to the swissuniversities grant I’m writing now (deadline friday :-(

A problem I see could be the licenses of the triple store. But - as I talked to Ivan - we plan to integrate Jena (without fuseki) again later in time...

Let’s talk about the possibilities ASAP together!

Lukas

Sent from my iPad

On 10 Feb 2018, at 11:30, janCstoffregen <notifications@github.com<mailto:notifications@github.com>> wrote:


Dear @benjamingeer<https://github.com/benjamingeer> ,
I did not want to say anything against the capability of the system, I'd like to honestly apologise if it sounded like this.

A quick start guide is a great idea, I will be glad to assist in writing it and will start right away, thank you for this suggestion.

I meant the dhlab fork, sorry for this mistake.

I disagree that 30 pages are necessary to get the system up and running. I agree that you need extensive documentation to use the system in depth and to further develop it, but not to get it up and running. That is not common since you can automise most steps. For instance, I would like to mention in the documentation how to set up sipi on centos that there is a sipi - base docker image, so that the user does not have to install all packages manually any more.

Thank you very much for your answer and best regards,
Jan

**Comment by janCstoffregen** [comment]
Done as discussed here. 
https://github.com/nie-ine/Quick-Installation-Guide---Knora-Salsah-Sipi-GraphDB
