### ISSUE TITLE
Error concerning StringV2

### ISSUE THREAD

**Issue by sofiag** [dhlab-basel/Salsah#170]
Sometimes when runing ng s I get the error: 
"
ERROR in src/app/view/modules/form/edit-list-info/edit-list-info.component.ts(6,9): error TS2305: Module '"/Users/SofiaG/Salsah/src/app/model/webapi/knora/v2/shared/strings"' has no exported member 'StringV2'.
"

StringV2 is imported properly and the same branch works without problems on my computer at work.

The error is non-persistent, meaning sometimes I can run it without problems, and it is not clear to me what triggers it.

**Comment by subotic** [comment]
is this happening on the `wip/edit-list-info-#162` branch?

**Comment by sofiag** [comment]
Right now yes

**Comment by musicEnfanthen** [comment]
It shouldn’t work at any computer, because, as far I can see, there is really no exported member `StringV2` in '/src/app/model/webapi/knora/v2/shared/strings', but only `StringLitervalV2` (see: [https://github.com/dhlab-basel/Salsah/blob/wip/edit-list-info-%23162/src/app/model/webapi/knora/v2/shared/strings.ts](https://github.com/dhlab-basel/Salsah/blob/wip/edit-list-info-%23162/src/app/model/webapi/knora/v2/shared/strings.ts))

**Comment by sofiag** [comment]
@musicEnfanthen Thanks, I don't know why this update to StringLiteralV2 didn't at least show up when I merged from develop. I might have a problem with my local git branches on my laptop. 

@subotic  It used to be StringV2 or am I hallucinating?

**Comment by subotic** [comment]
>  It used to be StringV2 or am I hallucinating?

No, it was. Sorry, must've renamed it, so that it has the same name as the corresponding class in `webapi`.

**Comment by sofiag** [comment]
@subotic pfiou (cold sweat)! :-D ok!!
